// playgrounds/angular/src/app/app.component.ts
import { Component } from '@angular/core'
import { instantMeiliSearch } from '../../../../src'

const searchClient = instantMeiliSearch(
  // 'https://demos.meilisearch.com',
  // 'dc3fedaf922de8937fdea01f0a7d59557f1fd31832cb8440ce94231cfdde7f25'
  'http://localhost:7700',
  'masterKey'
)

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-app'
  config = {
    indexName: 'steam-video-games',
    searchClient,
  }
}

<header class="header">
  <h1 class="header-title">Meilisearch + Angular InstantSearch</h1>
  <p class="header-subtitle">Search in Steam video games 🎮</p>

</header>

<div class="container">
  <ais-instantsearch [config]="config">
    <ais-stats></ais-stats>
    <div class="search-panel">
      <div class="search-panel__filters">
        <ais-clear-refinements></ais-clear-refinements>
        <ais-sort-by [items]="[
          { value: 'steam-video-games', label: 'Relevant' },
          {
            value: 'steam-video-games:recommendationCount:desc',
            label: 'Most Recommended'
          },
          {
            value: 'steam-video-games:recommendationCount:asc',
            label: 'Least Recommended'
          }
          ]"></ais-sort-by>
        <ais-configure
          [searchParameters]="{ hitsPerPage: 6, attributesToSnippet: ['description:10'], snippetEllipsisText:'...' }">
        </ais-configure>
        <h2>Genres</h2>
        <ais-refinement-list attribute="genres"></ais-refinement-list>
        <h2>Players</h2>
        <ais-refinement-list attribute="players"></ais-refinement-list>
        <h2>Platforms</h2>
        <ais-refinement-list attribute="platforms"></ais-refinement-list>
        <h2>Misc</h2>
        <ais-refinement-list attribute="misc"></ais-refinement-list>
      </div>

      <div class="search-panel__results">
        <div class="searchbox">
          <ais-search-box placeholder=""></ais-search-box>
        </div>

        <ais-hits>
          <ng-template let-hits="hits">
            <div *ngIf="hits.length === 0">
              No results found matching <strong></strong>.
            </div>
            <ol class="ais-Hits-list">
              <li *ngFor="let hit of hits" class="ais-Hits-item">
                <img src="{{hit.image}}" alt="{{hit.name}}" align="left" />
                <div class="hit-name">
                  <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
                </div>
                <div class="hit-description">
                  <ais-snippet attribute="description" [hit]="hit">
                  </ais-snippet>
                </div>
                <div class="hit-info">price: ${{hit.price}}</div>
                <div class="hit-info">Release date: {{hit.releaseDate}}</div>
                <div class="hit-info">Recommendation: {{hit.recommendationCount}}</div>
              </li>
            </ol>
          </ng-template>
        </ais-hits>

        <div class="pagination">
          <ais-pagination></ais-pagination>
        </div>
      </div>

    </div>
  </ais-instantsearch>
</div>

// playgrounds/local-react/src/App.jsx
import 'instantsearch.css/themes/algolia-min.css'
import React from 'react'
import {
  InstantSearch,
  InfiniteHits,
  SearchBox,
  Stats,
  Highlight,
  ClearRefinements,
  RefinementList,
  Configure,
  SortBy,
  Snippet,
} from 'react-instantsearch-dom'

import './App.css'
import { instantMeiliSearch } from '@meilisearch/instant-meilisearch'

const searchClient = instantMeiliSearch('http://localhost:7700', 'masterKey', {
  primaryKey: 'id',
})

const App = () => (
  <div className="ais-InstantSearch">
    <h1>Meilisearch + React InstantSearch</h1>
    <h2>
      Search in Steam video games{' '}
      <span role="img" aria-label="emoji">
        🎮
      </span>
    </h2>
    <p>
      This is not the official Steam dataset but only for demo purpose. Enjoy
      searching with Meilisearch!
    </p>
    <InstantSearch indexName="steam-video-games" searchClient={searchClient}>
      <Stats />
      <div className="left-panel">
        <ClearRefinements />
        <SortBy
          defaultRefinement="steam-video-games"
          items={[
            { value: 'steam-video-games', label: 'Relevant' },
            {
              value: 'steam-video-games:recommendationCount:desc',
              label: 'Most Recommended',
            },
            {
              value: 'steam-video-games:recommendationCount:asc',
              label: 'Least Recommended',
            },
          ]}
        />
        <h2>Genres</h2>
        <RefinementList attribute="genres" />
        <h2>Players</h2>
        <RefinementList attribute="players" />
        <h2>Platforms</h2>
        <RefinementList attribute="platforms" />
        <h2>Misc</h2>
        <RefinementList attribute="misc" />
        <Configure
          hitsPerPage={6}
          attributesToSnippet={['description:50']}
          snippetEllipsisText={'...'}
        />
      </div>
      <div className="right-panel">
        <SearchBox />
        <InfiniteHits hitComponent={Hit} />
      </div>
    </InstantSearch>
  </div>
)

const Hit = ({ hit }) => {
  return (
    <div key={hit.id}>
      <div className="hit-name">
        <Highlight attribute="name" hit={hit} />
      </div>
      <div className="hit-name">
        <Highlight attribute="genres" hit={hit} />
      </div>
      <img src={hit.image} align="left" alt={hit.name} />
      <div className="hit-name">
        <Snippet attribute="description" hit={hit} />
      </div>
      <div className="hit-info">
        <b>price:</b> {hit.price}
      </div>
      <div className="hit-info">
        <b>release date:</b> {hit.releaseDate}
      </div>
      <div className="hit-info">
        <b>Recommended:</b> {hit.recommendationCount}
      </div>
    </div>
  )
}

export default App
